name: Quality checks

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
    type: [opened, synchronized]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Installing dependencies
        run: npm ci
      - run: npm run eslint
      - run: npm test
      - run: npm run build
