name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependecies
        run: npm install
      - name: Check style
        run: npm run eslint
      - run: npm test
      - run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Notify Discord - Failure
        if: ${{success() && github.event_name == 'push'}}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            {
              "embeds": [{
                "title": "❌ Build Failed!",
                "description": "The pipeline encountered an error",
                "color": 15158332,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "${{ github.repository }}"
                  },
                  {
                    "name": "Branch",
                    "value": "${{ github.ref_name }}"
                  },
                  {
                    "name": "Commit",
                    "value": "${{ github.sha }}"
                  },
                  {
                    "name": "Message",
                    "value": "${{ github.event.head_commit.message }}"
                  },
                  {
                    "name": "Author",
                    "value": "${{ github.event.head_commit.author.name }}"
                  },
                  {
                    "name": "Workflow",
                    "value": "${{ github.workflow }}"
                  },
                  {
                    "name": "Job",
                    "value": "${{ github.job }}"
                  }
                ]
              }]
            }
      - name: Notify Discord - Success
        if: ${{success() && github.event_name == 'push'}}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            {
              "embeds": [{
                "title": "✅ Deployment Successful!",
                "description": "A new version was deployed to production",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Commit",
                    "value": "${{ github.sha }}",
                    "inline": false
                  },
                  {
                    "name": "Message",
                    "value": "${{ github.event.head_commit.message }}",
                    "inline": false
                  },
                  {
                    "name": "Author",
                    "value": "${{ github.event.head_commit.author.name }}",
                    "inline": false
                  }
                ]
              }]
            }

  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_PREFIX: v
